spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/retail_store_discount?useSSL=true
    username: root
    password: root
    initialization-mode: always





